# Запуск приложения и базы данных PostgreSQL в контейнерах
# Команда для запуска: docker compose up --build
services:
  backend:
    build: .
    container_name: video_stats_bot
    restart: unless-stopped

    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"